services:
  postgres:
    image: "postgres:16"
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"

  app:
    depends_on:
      - "postgres"
    build: .
    command: bash -c "rm -f /usr/src/app/tmp/pids/server.pid && (bundle check || bundle install) && ./bin/dev"
    stdin_open: true
    tty: true
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - gems:/gems
    environment:
      - TEST_DATABASE_HOST=postgres

volumes:
  postgres:
  gems:
